/*global systemDictionary:true */
'use strict';

systemDictionary = {
	"Link from ice warning": {
		"en": "Link from ice warning",
		"de": "Link von Eiswarnung",
		"ru": "Ссылка с ледового предупреждения",
		"pt": "Link do aviso de gelo",
		"nl": "Link van ijswaarschuwing",
		"fr": "Lien de l'avertissement de glace",
		"it": "Collegamento da avviso di ghiaccio",
		"es": "Enlace de advertencia de hielo",
		"pl": "Link z ostrzeżenia o lodzie",
		"zh-cn": "来自冰警告的链接"
    },
	"APIK1": {
		"en": "API-key",
		"de": "API-Schlüssel",
		"ru": "API-ключ",
		"pt": "Chave API",
		"nl": "API sleutel",
		"fr": "Clé API",
		"it": "Chiave API",
		"es": "Clave API",
		"pl": "Klucz API",
		"zh-cn": "API密钥"
    },
	"APIK2": {
		"en": "API-key",
		"de": "API-Schlüssel",
		"ru": "API-ключ",
		"pt": "Chave API",
		"nl": "API sleutel",
		"fr": "Clé API",
		"it": "Chiave API",
		"es": "Clave API",
		"pl": "Klucz API",
		"zh-cn": "API密钥"
	},
	"APIK3": {
		"en": "API-key",
		"de": "API-Schlüssel",
		"ru": "API-ключ",
		"pt": "Chave API",
		"nl": "API sleutel",
		"fr": "Clé API",
		"it": "Chiave API",
		"es": "Clave API",
		"pl": "Klucz API",
		"zh-cn": "API密钥"
	},
	"APIK4": {
		"en": "API-key",
		"de": "API-Schlüssel",
		"ru": "API-ключ",
		"pt": "Chave API",
		"nl": "API sleutel",
		"fr": "Clé API",
		"it": "Chiave API",
		"es": "Clave API",
		"pl": "Klucz API",
		"zh-cn": "API密钥"
	},
	"https://api.eiswarnung.de/": {
		"en": "https://api.eiswarnung.de/",
		"de": "https://api.eiswarnung.de/",
		"ru": "https://api.eiswarnung.de/",
		"pt": "https://api.eiswarnung.de/",
		"nl": "https://api.eiswarnung.de/",
		"fr": "https://api.eiswarnung.de/",
		"it": "https://api.eiswarnung.de/",
		"es": "https://api.eiswarnung.de/",
		"pl": "https://api.eiswarnung.de/",
		"zh-cn": "https://api.eiswarnung.de/"
	},
    "longitude1": {
		"en": "longitude",
		"de": "Längengrad",
		"ru": "долгота",
		"pt": "longitude",
		"nl": "Lengtegraad",
		"fr": "longitude",
		"it": "longitudine",
		"es": "longitud",
		"pl": "długość geograficzna",
		"zh-cn": "经度"
    },
	"longitude2": {
		"en": "longitude",
		"de": "Längengrad",
		"ru": "долгота",
		"pt": "longitude",
		"nl": "Lengtegraad",
		"fr": "longitude",
		"it": "longitudine",
		"es": "longitud",
		"pl": "długość geograficzna",
		"zh-cn": "经度"
	},
	"longitude3": {
		"en": "longitude",
		"de": "Längengrad",
		"ru": "долгота",
		"pt": "longitude",
		"nl": "Lengtegraad",
		"fr": "longitude",
		"it": "longitudine",
		"es": "longitud",
		"pl": "długość geograficzna",
		"zh-cn": "经度"
	},
	"longitude4": {
		"en": "longitude",
		"de": "Längengrad",
		"ru": "долгота",
		"pt": "longitude",
		"nl": "Lengtegraad",
		"fr": "longitude",
		"it": "longitudine",
		"es": "longitud",
		"pl": "długość geograficzna",
		"zh-cn": "经度"
	},
    "latitude1": {
		"en": "latitude",
		"de": "Breite",
		"ru": "широта",
		"pt": "latitude",
		"nl": "breedtegraad",
		"fr": "latitude",
		"it": "latitudine",
		"es": "latitud",
		"pl": "szerokość",
		"zh-cn": "纬度"
    },
	"latitude2": {
		"en": "latitude",
		"de": "Breite",
		"ru": "широта",
		"pt": "latitude",
		"nl": "breedtegraad",
		"fr": "latitude",
		"it": "latitudine",
		"es": "latitud",
		"pl": "szerokość",
		"zh-cn": "纬度"
	},
	"latitude3": {
		"en": "latitude",
		"de": "Breite",
		"ru": "широта",
		"pt": "latitude",
		"nl": "breedtegraad",
		"fr": "latitude",
		"it": "latitudine",
		"es": "latitud",
		"pl": "szerokość",
		"zh-cn": "纬度"
	},
	"latitude4": {
		"en": "latitude",
		"de": "Breite",
		"ru": "широта",
		"pt": "latitude",
		"nl": "breedtegraad",
		"fr": "latitude",
		"it": "latitudine",
		"es": "latitud",
		"pl": "szerokość",
		"zh-cn": "纬度"
	},
	"location_active1": {
		"en": "active location",
		"de": "aktiver Standort",
		"ru": "активное место",
		"pt": "localização ativa",
		"nl": "actieve locatie",
		"fr": "emplacement actif",
		"it": "posizione attiva",
		"es": "ubicación activa",
		"pl": "aktywna lokalizacja",
		"zh-cn": "活动地点"
	},
	"location_active2": {
		"en": "active location",
		"de": "aktiver Standort",
		"ru": "активное место",
		"pt": "localização ativa",
		"nl": "actieve locatie",
		"fr": "emplacement actif",
		"it": "posizione attiva",
		"es": "ubicación activa",
		"pl": "aktywna lokalizacja",
		"zh-cn": "活动地点"
	},
	"location_active3": {
		"en": "active location",
		"de": "aktiver Standort",
		"ru": "активное место",
		"pt": "localização ativa",
		"nl": "actieve locatie",
		"fr": "emplacement actif",
		"it": "posizione attiva",
		"es": "ubicación activa",
		"pl": "aktywna lokalizacja",
		"zh-cn": "活动地点"
	},
	"location_active4": {
		"en": "active location",
		"de": "aktiver Standort",
		"ru": "активное место",
		"pt": "localização ativa",
		"nl": "actieve locatie",
		"fr": "emplacement actif",
		"it": "posizione attiva",
		"es": "ubicación activa",
		"pl": "aktywna lokalizacja",
		"zh-cn": "活动地点"
	},
	"Location_Name1": {
		"en": "location name",
		"de": "Standortnamen",
		"ru": "название местоположения",
		"pt": "nome do local",
		"nl": "locatie naam",
		"fr": "nom de la localisation",
		"it": "nome del luogo",
		"es": "nombre del lugar",
		"pl": "Nazwa lokalizacji",
		"zh-cn": "地点名称"
	},
	"Location_Name2": {
		"en": "location name",
		"de": "Standortnamen",
		"ru": "название местоположения",
		"pt": "nome do local",
		"nl": "locatie naam",
		"fr": "nom de la localisation",
		"it": "nome del luogo",
		"es": "nombre del lugar",
		"pl": "Nazwa lokalizacji",
		"zh-cn": "地点名称"
	},
	"Location_Name3": {
		"en": "location name",
		"de": "Standortnamen",
		"ru": "название местоположения",
		"pt": "nome do local",
		"nl": "locatie naam",
		"fr": "nom de la localisation",
		"it": "nome del luogo",
		"es": "nombre del lugar",
		"pl": "Nazwa lokalizacji",
		"zh-cn": "地点名称"
	},
	"Location_Name4": {
		"en": "location name",
		"de": "Standortnamen",
		"ru": "название местоположения",
		"pt": "nome do local",
		"nl": "locatie naam",
		"fr": "nom de la localisation",
		"it": "nome del luogo",
		"es": "nombre del lugar",
		"pl": "Nazwa lokalizacji",
		"zh-cn": "地点名称"
	},
	"mail_active1": {
		"en": "active mail",
		"de": "aktive Mail",
		"ru": "активная почта",
		"pt": "correio ativo",
		"nl": "actieve mail",
		"fr": "courrier actif",
		"it": "posta attiva",
		"es": "correo activo",
		"pl": "aktywna poczta",
		"zh-cn": "活动邮件"
	},
	"mail_active2": {
		"en": "active mail",
		"de": "aktive Mail",
		"ru": "активная почта",
		"pt": "correio ativo",
		"nl": "actieve mail",
		"fr": "courrier actif",
		"it": "posta attiva",
		"es": "correo activo",
		"pl": "aktywna poczta",
		"zh-cn": "活动邮件"
	},
	"mail_active3": {
		"en": "active mail",
		"de": "aktive Mail",
		"ru": "активная почта",
		"pt": "correio ativo",
		"nl": "actieve mail",
		"fr": "courrier actif",
		"it": "posta attiva",
		"es": "correo activo",
		"pl": "aktywna poczta",
		"zh-cn": "活动邮件"
	},
	"mail_active4": {
		"en": "active mail",
		"de": "aktive Mail",
		"ru": "активная почта",
		"pt": "correio ativo",
		"nl": "actieve mail",
		"fr": "courrier actif",
		"it": "posta attiva",
		"es": "correo activo",
		"pl": "aktywna poczta",
		"zh-cn": "活动邮件"
	},
	"email_from1": {
		"en": "email from",
		"de": "E-Mail von",
		"ru": "электронное письмо от",
		"pt": "e-mail de",
		"nl": "E-mail van",
		"fr": "email de",
		"it": "e-mail da",
		"es": "email de",
		"pl": "E-mail z",
		"zh-cn": "电子邮件来自"
	},
	"email_from2": {
		"en": "email from",
		"de": "E-Mail von",
		"ru": "электронное письмо от",
		"pt": "e-mail de",
		"nl": "E-mail van",
		"fr": "email de",
		"it": "e-mail da",
		"es": "email de",
		"pl": "E-mail z",
		"zh-cn": "电子邮件来自"
	},
	"email_from3": {
		"en": "email from",
		"de": "E-Mail von",
		"ru": "электронное письмо от",
		"pt": "e-mail de",
		"nl": "E-mail van",
		"fr": "email de",
		"it": "e-mail da",
		"es": "email de",
		"pl": "E-mail z",
		"zh-cn": "电子邮件来自"
	},
	"email_from4": {
		"en": "email from",
		"de": "E-Mail von",
		"ru": "электронное письмо от",
		"pt": "e-mail de",
		"nl": "E-mail van",
		"fr": "email de",
		"it": "e-mail da",
		"es": "email de",
		"pl": "E-mail z",
		"zh-cn": "电子邮件来自"
	},
	"email_to1": {
		"en": "email to",
		"de": "E-Mail an",
		"ru": "электронное письмо на",
		"pt": "email para",
		"nl": "email naar",
		"fr": "envoyer à",
		"it": "invia una email a",
		"es": "Email para",
		"pl": "Wyślij email do",
		"zh-cn": "发邮件给"
	},
	"email_to2": {
		"en": "email to",
		"de": "E-Mail an",
		"ru": "электронное письмо на",
		"pt": "email para",
		"nl": "email naar",
		"fr": "envoyer à",
		"it": "invia una email a",
		"es": "Email para",
		"pl": "Wyślij email do",
		"zh-cn": "发邮件给"
	},
	"email_to3": {
		"en": "email to",
		"de": "E-Mail an",
		"ru": "электронное письмо на",
		"pt": "email para",
		"nl": "email naar",
		"fr": "envoyer à",
		"it": "invia una email a",
		"es": "Email para",
		"pl": "Wyślij email do",
		"zh-cn": "发邮件给"
	},
	"email_to4": {
		"en": "email to",
		"de": "E-Mail an",
		"ru": "электронное письмо на",
		"pt": "email para",
		"nl": "email naar",
		"fr": "envoyer à",
		"it": "invia una email a",
		"es": "Email para",
		"pl": "Wyślij email do",
		"zh-cn": "发邮件给"
	},
	"email_subject1": {
		"en": "email  subject",
		"de": "E-Mail Betreff",
		"ru": "Тема письма",
		"pt": "assunto do email",
		"nl": "e-mail onderwerp",
		"fr": "Sujet du courriel",
		"it": "oggetto dell'email",
		"es": "asunto del email",
		"pl": "temat emaila",
		"zh-cn": "电子邮件主题"
	},
	"email_subject2": {
		"en": "email  subject",
		"de": "E-Mail Betreff",
		"ru": "Тема письма",
		"pt": "assunto do email",
		"nl": "e-mail onderwerp",
		"fr": "Sujet du courriel",
		"it": "oggetto dell'email",
		"es": "asunto del email",
		"pl": "temat emaila",
		"zh-cn": "电子邮件主题"
	},
	"email_subject3": {
		"en": "email  subject",
		"de": "E-Mail Betreff",
		"ru": "Тема письма",
		"pt": "assunto do email",
		"nl": "e-mail onderwerp",
		"fr": "Sujet du courriel",
		"it": "oggetto dell'email",
		"es": "asunto del email",
		"pl": "temat emaila",
		"zh-cn": "电子邮件主题"
	},
	"email_subject4": {
		"en": "email  subject",
		"de": "E-Mail Betreff",
		"ru": "Тема письма",
		"pt": "assunto do email",
		"nl": "e-mail onderwerp",
		"fr": "Sujet du courriel",
		"it": "oggetto dell'email",
		"es": "asunto del email",
		"pl": "temat emaila",
		"zh-cn": "电子邮件主题"
	},
	"email_message1": {
		"en": "email message",
		"de": "E-Mail Nachricht",
		"ru": "сообщение электронной почты",
		"pt": "mensagem de email",
		"nl": "email bericht",
		"fr": "message électronique",
		"it": "messaggio email",
		"es": "Mensaje de correo electrónico",
		"pl": "wiadomość e-mail",
		"zh-cn": "电子邮件"
	},
	"email_message2": {
		"en": "email message",
		"de": "E-Mail Nachricht",
		"ru": "сообщение электронной почты",
		"pt": "mensagem de email",
		"nl": "email bericht",
		"fr": "message électronique",
		"it": "messaggio email",
		"es": "Mensaje de correo electrónico",
		"pl": "wiadomość e-mail",
		"zh-cn": "电子邮件"
	},
	"email_message3": {
		"en": "email message",
		"de": "E-Mail Nachricht",
		"ru": "сообщение электронной почты",
		"pt": "mensagem de email",
		"nl": "email bericht",
		"fr": "message électronique",
		"it": "messaggio email",
		"es": "Mensaje de correo electrónico",
		"pl": "wiadomość e-mail",
		"zh-cn": "电子邮件"
	},
	"email_message4": {
		"en": "email message",
		"de": "E-Mail Nachricht",
		"ru": "сообщение электронной почты",
		"pt": "mensagem de email",
		"nl": "email bericht",
		"fr": "message électronique",
		"it": "messaggio email",
		"es": "Mensaje de correo electrónico",
		"pl": "wiadomość e-mail",
		"zh-cn": "电子邮件"
	},

};






